apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default  # Mevcut bir ad alan覺 ad覺n覺 buraya yaz覺n
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
